language: php
php:
  - '5.3'
  - '5.4.45'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly
os:
  - linux

before_install:
  - composer self-update
  - composer install

script: phpunit --verbose --debug
